[conduit]
server ansible_host=74.248.114.135 ansible_user=azureuser

[conduit:vars]
repo_url=https://github.com/gopay-kg/devsecops-conduit-test.git
site_name=conduit.dastanko.dpdns.org
ansible_ssh_common_args=-o UserKnownHostsFile=deploy/known_hosts -o StrictHostKeyChecking=yes
